import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:path_provider/path_provider.dart';
import 'package:video_player/video_player.dart';
import 'package:video_thumbnail/video_thumbnail.dart' as vt;

import '../../controllers/app_config_controller.dart';
import '../../controllers/auth_controller.dart';
import '../../controllers/upload_controller.dart';
import '../../models/expert_post.dart';
import '../../screens/social/mock_social_data.dart' as mock;
import '../../screens/social/social_tokens.dart';
import '../../services/community_service.dart';
import '../../services/expert_post_service.dart';
import '../../services/upload_service.dart';
import '../../utils/haptic_utils.dart';
import '../../utils/responsive.dart';
import '../../widgets/dismiss_keyboard_on_tap.dart';

/// Composer for a new expert post — pick **type** first (article / video /
/// reel), then fill in the relevant fields, then publish.
///
/// Pops with the freshly-created [ExpertPost] on success so the caller (the
/// studio dashboard) can prepend it without a full refresh.
///
/// In **edit mode** (pass [existingPost]) the form is pre-populated and the
/// save button calls PATCH instead of POST. Pops with the updated post on
/// success.
class CreatePostScreen extends StatefulWidget {
  /// When non-null, the screen runs in edit mode for this existing post.
  final ExpertPost? existingPost;

  const CreatePostScreen({super.key}) : existingPost = null;

  /// Edit an existing post. Title / body / media url / cover url /
  /// duration / visibility / tickers are pre-filled; the type is fixed
  /// (you can't change article ↔ video on an existing row).
  const CreatePostScreen.edit({super.key, required ExpertPost post})
      : existingPost = post;

  bool get isEditing => existingPost != null;

  @override
  State<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends State<CreatePostScreen> {
  final _formKey = GlobalKey<FormState>();
  final _title = TextEditingController();
  final _body = TextEditingController();
  final _mediaUrl = TextEditingController();
  final _coverUrl = TextEditingController();
  final _duration = TextEditingController();
  final _tickerInput = TextEditingController();
  final List<String> _tickers = [];

  PostType _type = PostType.article;
  PostVisibility _visibility = PostVisibility.subscribersOnly;
  bool _publishing = false;
  String? _error;

  // ── Destination picker state ────────────────────────────────────
  // The composer can fan-out to:
  //   * the expert's own profile (default ON),
  //   * any community the expert has joined (article-only — the
  //     community endpoint doesn't accept video/reel media).
  //
  // [_destinations] is the joined-community catalog used to render
  // the checkbox list. Loaded once on initState via the backend's
  // /me/communities endpoint, then cross-referenced against the
  // mock Community data for display name + region color (until
  // a real /communities/:id GET is wired through).
  bool _publishToProfile = true;
  final Set<String> _selectedCommunities = <String>{};
  List<mock.Community> _destinations = const [];
  bool _destinationsLoaded = false;
  /// Required by the community endpoint when posting an article.
  /// Stays `HOLD` by default; only surfaced in the UI when at
  /// least one community is selected.
  String _stance = 'HOLD';

  // ── Media-picker state (video / cover) ──
  // Once a file is picked we upload it to the backend and store the resulting
  // URL on _mediaUrl / _coverUrl. While the upload is in flight, we show a
  // spinner instead of the picked-file row so the user can't double-tap.
  File? _pickedVideoLocal;
  File? _pickedCoverLocal;
  bool _uploadingVideo = false;
  /// 0..1 progress of the chunked video upload. Driven by the
  /// onProgress callback from [UploadService.uploadVideoChunked]. Stays
  /// at 0 while resolving init / probing duration; ramps up as chunks
  /// land; reaches 1.0 right before /complete fires.
  double _videoUploadProgress = 0.0;
  bool _uploadingCover = false;
  String? _mediaPickError;

  /// True when the cover was auto-generated by snapping a frame from the
  /// uploaded video. Drives a small "Auto-generated" hint on the cover
  /// picker tile + the "Replace" affordance for overriding it.
  bool _coverIsAuto = false;

  // Global background-upload manager + listeners that mirror its progress
  // and result back into this screen, so the inline tile and the global
  // UploadStatusPill stay in sync — and the upload keeps running if the
  // user leaves this screen mid-upload.
  late final UploadController _uploadCtrl;
  Worker? _progWorker;
  Worker? _phaseWorker;

  @override
  void initState() {
    super.initState();
    _uploadCtrl = Get.find<UploadController>();
    _uploadingVideo = _uploadCtrl.isActive;
    _progWorker = ever<double>(_uploadCtrl.progress, (p) {
      if (mounted) setState(() => _videoUploadProgress = p);
    });
    _phaseWorker = ever<UploadPhase>(_uploadCtrl.phase, (ph) {
      if (!mounted) return;
      setState(() {
        _uploadingVideo = _uploadCtrl.isActive;
        if (ph == UploadPhase.success) {
          final url = _uploadCtrl.resultUrl.value;
          if (url != null && url.isNotEmpty) _mediaUrl.text = url;
        } else if (ph == UploadPhase.failed) {
          _pickedVideoLocal = null;
          _mediaPickError = _uploadCtrl.error.value;
        }
      });
    });
    final existing = widget.existingPost;
    if (existing != null) {
      // Edit mode — pre-fill every field from the existing post.
      _type = existing.postType;
      _visibility = existing.visibility;
      _title.text = existing.title ?? '';
      _body.text = existing.body;
      _mediaUrl.text = existing.mediaUrl ?? '';
      _coverUrl.text = existing.coverUrl ?? '';
      _duration.text =
          existing.durationSeconds != null ? '${existing.durationSeconds}' : '';
      _tickers.addAll(existing.tickers);
    } else {
      // New-post mode only — load joined communities so the
      // destination picker can render. Edit mode keeps the legacy
      // single-target flow (you can't change targetType after
      // publish).
      _loadDestinations();
    }
  }

  /// Pull the list of communities the expert has joined and
  /// cross-reference the mock community catalog for display
  /// metadata. Failure leaves the destination list empty — the
  /// picker degrades to "Profile only" gracefully.
  Future<void> _loadDestinations() async {
    // Community kill-switch — when communities are disabled, don't offer
    // any community destinations; the composer degrades to "Profile only".
    if (!Get.find<AppConfigController>().communityEnabled.value) {
      if (mounted) setState(() => _destinationsLoaded = true);
      return;
    }
    final res = await CommunityService.myCommunityIds();
    if (!mounted) return;
    final ids = res.ids ?? const <String>{};
    final list = <mock.Community>[];
    for (final entry in mock.MockSocialData.communities) {
      if (ids.contains(entry.id)) list.add(entry);
    }
    setState(() {
      _destinations = list;
      _destinationsLoaded = true;
    });
  }

  @override
  void dispose() {
    _progWorker?.dispose();
    _phaseWorker?.dispose();
    _title.dispose();
    _body.dispose();
    _mediaUrl.dispose();
    _coverUrl.dispose();
    _duration.dispose();
    _tickerInput.dispose();
    super.dispose();
  }

  /// Pick a video, validate its duration, then upload it to the backend.
  /// On success, _mediaUrl is filled with the absolute URL the backend
  /// served back. For reels, rejects anything > 60s with a friendly inline
  /// error.
  Future<void> _pickAndUploadVideo() async {
    setState(() => _mediaPickError = null);

    final result = await FilePicker.platform.pickFiles(
      type: FileType.video,
      allowMultiple: false,
      withData: false,
    );
    if (result == null || result.files.single.path == null) return;
    final file = File(result.files.single.path!);

    // Show "Reading video…" in the global pill while we probe duration —
    // the step that used to feel like a silent freeze.
    _uploadCtrl.beginReading('Reading video…');

    // Inspect duration via video_player itself — works for any container
    // VideoPlayerController can later play back, which is exactly the set
    // of files we accept anyway. Time-boxed so a stubborn file can't hang
    // the picker forever — on timeout we just skip the length check.
    int seconds;
    final probe = VideoPlayerController.file(file);
    try {
      await probe.initialize().timeout(const Duration(seconds: 20));
      final dur = probe.value.duration;
      seconds = dur.inSeconds;
    } catch (e) {
      _uploadCtrl.cancelReading();
      setState(() => _mediaPickError =
          'createPostX.couldNotReadVideo'.trParams({'error': '$e'}));
      await probe.dispose();
      return;
    }
    await probe.dispose();

    if (seconds <= 0) {
      _uploadCtrl.cancelReading();
      setState(() => _mediaPickError =
          'createPostX.couldNotDetectDuration'.tr);
      return;
    }
    if (_type == PostType.reel && seconds > 60) {
      _uploadCtrl.cancelReading();
      final m = seconds ~/ 60;
      final s = seconds % 60;
      setState(() => _mediaPickError = 'createPostX.reelTooLong'.trParams(
          {'duration': '$m:${s.toString().padLeft(2, '0')}'}));
      return;
    }

    setState(() {
      _pickedVideoLocal = file;
      _uploadingVideo = true;
      _videoUploadProgress = 0.0;
      _duration.text = '$seconds';
    });

    // Hand the transfer to the global UploadController. It owns the
    // direct-to-S3, resumable upload, so it KEEPS RUNNING if the user
    // leaves this screen — the floating UploadStatusPill shows progress on
    // every screen. The `ever` listeners wired in initState mirror its
    // progress + final URL back into this screen (and surface any error on
    // _mediaPickError). Fire-and-forget so the composer stays interactive.
    _uploadCtrl.startVideoUpload(file);

    // Auto-generate a cover from the video — only when the user hasn't
    // already picked one. Sarah's manual cover always wins.
    if (_coverUrl.text.trim().isEmpty) {
      // Choose a frame near the start: 1s for normal-length clips, the
      // first frame if the clip is shorter than that.
      final atMs = seconds >= 1 ? 1000 : 0;
      await _generateAutoCover(file, atMs);
    }
  }

  /// Snap a frame from [video] at [atMs] milliseconds, upload it, and put
  /// the resulting URL on _coverUrl. Silently bails on failure — a missing
  /// cover just means the card shows a black frame with the play button,
  /// which is still functional.
  Future<void> _generateAutoCover(File video, int atMs) async {
    setState(() => _uploadingCover = true);
    try {
      final tmpDir = await getTemporaryDirectory();
      final outPath = await vt.VideoThumbnail.thumbnailFile(
        video: video.path,
        thumbnailPath: tmpDir.path,
        imageFormat: vt.ImageFormat.JPEG,
        timeMs: atMs,
        quality: 85,
        maxWidth: 720,
      );
      if (outPath == null || outPath.isEmpty) {
        if (mounted) setState(() => _uploadingCover = false);
        return;
      }
      final thumbFile = File(outPath);
      if (!thumbFile.existsSync()) {
        if (mounted) setState(() => _uploadingCover = false);
        return;
      }
      final res = await UploadService.uploadImage(thumbFile);
      if (!mounted) return;
      if (res.error != null || res.url == null) {
        // Cover upload failed — that's fine, post still works without it.
        setState(() => _uploadingCover = false);
        return;
      }
      setState(() {
        _uploadingCover = false;
        _pickedCoverLocal = thumbFile;
        _coverUrl.text = res.url!;
        _coverIsAuto = true;
      });
    } catch (_) {
      // Frame extraction can fail on weird codecs / permissions — just
      // skip it. The user can still pick a cover manually if they want.
      if (mounted) setState(() => _uploadingCover = false);
    }
  }

  /// Pick a cover image manually — overrides any auto-generated cover.
  /// No size/aspect-ratio validation client-side; backend caps at 8 MB.
  Future<void> _pickAndUploadCover() async {
    setState(() => _mediaPickError = null);

    final result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      allowMultiple: false,
      withData: false,
    );
    if (result == null || result.files.single.path == null) return;
    final file = File(result.files.single.path!);

    setState(() {
      _pickedCoverLocal = file;
      _uploadingCover = true;
      // Sarah picking her own cover always replaces the auto one.
      _coverIsAuto = false;
    });
    final res = await UploadService.uploadImage(file);
    if (!mounted) return;
    if (res.error != null) {
      setState(() {
        _uploadingCover = false;
        _pickedCoverLocal = null;
        _mediaPickError = res.error;
      });
      return;
    }
    setState(() {
      _uploadingCover = false;
      _coverUrl.text = res.url ?? '';
    });
  }

  void _clearVideo() {
    setState(() {
      _pickedVideoLocal = null;
      _mediaUrl.clear();
      _duration.clear();
      // Removing the video also wipes any auto-cover we generated for it.
      // Manual covers stay (Sarah might have intentionally set one).
      if (_coverIsAuto) {
        _pickedCoverLocal = null;
        _coverUrl.clear();
        _coverIsAuto = false;
      }
    });
  }

  void _clearCover() {
    setState(() {
      _pickedCoverLocal = null;
      _coverUrl.clear();
      _coverIsAuto = false;
    });
  }

  /// Save-as-draft path (mig 0020, item 4.15). Same field validation
  /// as publish but routes through `/me/expert/drafts` and skips the
  /// destination picker — drafts always live on the expert's own
  /// profile until the user explicitly publishes (and at publish-time
  /// the destination picker reappears in a future patch). For now,
  /// drafts are profile-scoped only.
  Future<void> _saveAsDraft() async {
    HapticUtils.tap();
    setState(() {
      _publishing = true;
      _error = null;
    });
    final res = await ExpertPostService.saveDraft(
      postType: _type,
      title: _title.text.trim().isEmpty ? null : _title.text.trim(),
      body: _body.text.trim().isEmpty ? null : _body.text.trim(),
      mediaUrl: _mediaUrl.text.trim().isEmpty ? null : _mediaUrl.text.trim(),
      coverUrl: _coverUrl.text.trim().isEmpty ? null : _coverUrl.text.trim(),
      durationSeconds: int.tryParse(_duration.text.trim()),
      visibility: _visibility,
      tickers: List.of(_tickers),
    );
    if (!mounted) return;
    setState(() => _publishing = false);
    if (res.error != null) {
      setState(() => _error = res.error);
      return;
    }
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text('createPostX.savedToDrafts'.tr),
      behavior: SnackBarBehavior.floating,
      duration: const Duration(seconds: 2),
    ));
    Navigator.of(context).pop(res.post);
  }

  Future<void> _publish() async {
    if (!_formKey.currentState!.validate()) return;
    HapticUtils.confirm();
    final auth = Get.find<AuthController>();
    // For new posts the expertId comes from the authed user (only experts
    // can publish). For edits, use the existing post's expertId so the URL
    // path resolves correctly even if auth scope is fuzzy.
    final expertId =
        widget.existingPost?.expertId ?? auth.user?.expertId;
    if (expertId == null) {
      setState(() => _error = 'createPostX.onlyExperts'.tr);
      return;
    }

    // ── Edit mode short-circuit ───────────────────────────────
    // Editing keeps the legacy single-target flow (no destination
    // picker). The `target_type` of an existing row can't change
    // after publish — that would mean copying the row across
    // tables.
    if (widget.isEditing) {
      setState(() {
        _publishing = true;
        _error = null;
      });
      final existing = widget.existingPost!;
      final result = await ExpertPostService.update(
        expertId: expertId,
        postId: existing.id,
        title: _title.text.trim(),
        body: _body.text.trim(),
        mediaUrl: _mediaUrl.text.trim(),
        coverUrl: _coverUrl.text.trim(),
        durationSeconds: int.tryParse(_duration.text.trim()),
        visibility: _visibility,
        tickers: _tickers,
      );
      if (!mounted) return;
      if (result.post != null) {
        Navigator.of(context).pop(result.post);
        return;
      }
      setState(() {
        _publishing = false;
        _error = result.error ?? 'createPostX.updateFailed'.tr;
      });
      return;
    }

    // ── New post mode: validate destinations ──────────────────
    // The user must select at least one place to publish. Profile
    // is selected by default; communities require an explicit
    // checkbox tick. Communities now accept all post types
    // (article, video, reel) so we no longer gate the eligible set
    // on type.
    final eligibleCommunities = _selectedCommunities;
    if (!_publishToProfile && eligibleCommunities.isEmpty) {
      setState(() =>
          _error = 'createPostX.pickDestination'.tr);
      return;
    }
    // Community endpoint requires a single ticker symbol; without one
    // the row would fail server-side. Surface the requirement here so
    // the user fixes it before we fire requests.
    if (eligibleCommunities.isNotEmpty && _tickers.isEmpty) {
      setState(() => _error =
          'createPostX.tickerRequired'.tr);
      return;
    }

    setState(() {
      _publishing = true;
      _error = null;
    });

    // Fan-out: capture each destination's result so we can show
    // partial-success / partial-failure feedback.
    ExpertPost? profileResult;
    String? profileError;
    final communityErrors = <String, String>{}; // communityId → error msg
    final communityNames = <String, String>{}; // communityId → display name
    for (final c in _destinations) {
      communityNames[c.id] = c.name;
    }

    if (_publishToProfile) {
      final result = await ExpertPostService.create(
        expertId: expertId,
        type: _type,
        visibility: _visibility,
        title: _title.text.trim(),
        body: _body.text.trim(),
        mediaUrl: _mediaUrl.text.trim().isEmpty ? null : _mediaUrl.text.trim(),
        coverUrl: _coverUrl.text.trim().isEmpty ? null : _coverUrl.text.trim(),
        durationSeconds: int.tryParse(_duration.text.trim()),
        tickers: _tickers,
      );
      profileResult = result.post;
      profileError = result.error;
    }

    // Community posts use the community endpoint. Single ticker is
    // taken from the first entry in [_tickers]; the stance picker
    // defaults to HOLD when not surfaced.
    final firstTicker = _tickers.isEmpty ? '' : _tickers.first;
    // Stance is meaningful for articles only; default HOLD silently
    // for video / reel community posts (the column is non-null on
    // the schema so we always send something).
    final outboundStance = _type == PostType.article ? _stance : 'HOLD';
    for (final cid in eligibleCommunities) {
      final res = await ExpertPostService.createCommunityPost(
        communityId: cid,
        type: _type,
        visibility: _visibility,
        title: _title.text.trim(),
        body: _body.text.trim(),
        ticker: firstTicker,
        stance: outboundStance,
        mediaUrl: _mediaUrl.text.trim().isEmpty ? null : _mediaUrl.text.trim(),
        coverUrl: _coverUrl.text.trim().isEmpty ? null : _coverUrl.text.trim(),
        durationSeconds: int.tryParse(_duration.text.trim()),
        tickers: _tickers,
      );
      if (res.error != null) {
        communityErrors[cid] = res.error!;
      }
    }

    if (!mounted) return;

    // ── Decide what to do based on results ────────────────────
    final anyProfileFail = _publishToProfile && profileError != null;
    final anyCommunityFail = communityErrors.isNotEmpty;
    final anySuccess = (_publishToProfile && profileResult != null) ||
        (eligibleCommunities.length > communityErrors.length);

    if (!anySuccess) {
      // Total failure — keep the screen open with the error.
      setState(() {
        _publishing = false;
        _error = profileError ?? communityErrors.values.first;
      });
      return;
    }

    // At least one destination succeeded. Pop with the profile post
    // (when we have one) so the studio can prepend it. Surface a
    // snackbar if any destination failed so the user knows what
    // didn't make it.
    if (anyProfileFail || anyCommunityFail) {
      final failed = <String>[];
      if (anyProfileFail) failed.add('createPostX.yourProfileFailLabel'.tr);
      for (final entry in communityErrors.entries) {
        failed.add(communityNames[entry.key] ?? entry.key);
      }
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          duration: const Duration(seconds: 4),
          content: Text(
            'createPostX.publishedButFailed'.trParams({'list': failed.join(', ')}),
          ),
        ),
      );
    }
    Navigator.of(context).pop(profileResult);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.isEditing ? 'createPostX.editTitle'.tr : 'createPostX.newTitle'.tr),
        actions: [
          // Step-20 (mig 0020, item 4.15) — composing a fresh post can
          // also save as a draft instead of publishing immediately.
          // Hidden in edit mode (existing posts use the regular Save).
          if (!widget.isEditing)
            IconButton(
              tooltip: 'createPostX.saveDraftTooltip'.tr,
              onPressed: _publishing ? null : _saveAsDraft,
              icon: const Icon(Icons.bookmark_outline_rounded),
            ),
          TextButton(
            onPressed: _publishing ? null : _publish,
            child: _publishing
                ? const SizedBox(
                    width: 18,
                    height: 18,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Text(widget.isEditing ? 'createPostX.save'.tr : 'createPostX.publish'.tr),
          ),
          const SizedBox(width: 4),
        ],
      ),
      body: SafeArea(
        child: DismissKeyboardOnTap(
        child: Form(
          key: _formKey,
          child: ListView(
            // iPad: center the composer to a comfortable column instead of
            // full-width fields. Phone: unchanged 16px inset.
            padding: EdgeInsets.fromLTRB(
                context.centeringHPad(contentWidth: 680), 12,
                context.centeringHPad(contentWidth: 680), 24),
            children: [
              // ── Card 1: Format ────────────────────────────────
              // The type picker drives which content fields show
              // below, so it's the first decision in the form.
              _Card(
                title: 'createPostX.cardFormat'.tr,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _TypePicker(
                      value: _type,
                      onChange: (t) => setState(() => _type = t),
                    ),
                    const SizedBox(height: 10),
                    Text(
                      _typeDescription(_type),
                      style: Theme.of(context).textTheme.bodySmall?.copyWith(
                            color: Theme.of(context).colorScheme.onSurfaceVariant,
                          ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 14),
              // ── Card 2: Content ───────────────────────────────
              // Type-specific fields (title / body / media).
              _Card(
                title: 'createPostX.cardContent'.tr,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: _fieldsForType(),
                ),
              ),
              const SizedBox(height: 14),
              // ── Card 3: Tickers ───────────────────────────────
              _Card(
                title: 'createPostX.cardTickers'.tr,
                titleSuffix: _tickers.isEmpty ? null : '${_tickers.length}',
                child: _TickerInput(
                  controller: _tickerInput,
                  items: _tickers,
                  onAdd: (v) =>
                      setState(() => _tickers.add(v.toUpperCase())),
                  onRemove: (i) => setState(() => _tickers.removeAt(i)),
                ),
              ),
              const SizedBox(height: 14),
              // ── Card 4: Audience (new posts only) ─────────────
              // Bundles visibility + destinations + stance into a
              // single card since they all answer "who sees this".
              if (!widget.isEditing) ...[
                _Card(
                  title: 'createPostX.cardAudience'.tr,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _SubLabel('createPostX.subVisibility'.tr),
                      const SizedBox(height: 8),
                      _VisibilityPicker(
                        value: _visibility,
                        onChange: (v) => setState(() => _visibility = v),
                      ),
                      const SizedBox(height: 18),
                      _SubLabel('createPostX.subPublishTo'.tr),
                      const SizedBox(height: 8),
                      _DestinationPicker(
                        publishToProfile: _publishToProfile,
                        onProfileChange: (v) =>
                            setState(() => _publishToProfile = v),
                        destinations: _destinations,
                        selectedCommunities: _selectedCommunities,
                        onCommunityToggle: (id) {
                          setState(() {
                            if (_selectedCommunities.contains(id)) {
                              _selectedCommunities.remove(id);
                            } else {
                              _selectedCommunities.add(id);
                            }
                          });
                        },
                        loaded: _destinationsLoaded,
                        communitiesEnabled: true,
                      ),
                      // Stance only when ≥ 1 community is selected
                      // and the type is article (community media
                      // posts default to HOLD silently).
                      if (_type == PostType.article &&
                          _selectedCommunities.isNotEmpty) ...[
                        const SizedBox(height: 18),
                        _SubLabel('createPostX.subStance'.tr),
                        const SizedBox(height: 8),
                        _StancePicker(
                          value: _stance,
                          onChange: (s) => setState(() => _stance = s),
                        ),
                      ],
                    ],
                  ),
                ),
              ] else ...[
                // Edit mode just gets the visibility toggle — no
                // destination switching after publish.
                _Card(
                  title: 'createPostX.cardVisibility'.tr,
                  child: _VisibilityPicker(
                    value: _visibility,
                    onChange: (v) => setState(() => _visibility = v),
                  ),
                ),
              ],
              if (_error != null) ...[
                const SizedBox(height: 16),
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Theme.of(context)
                        .colorScheme
                        .errorContainer
                        .withValues(alpha: 0.4),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.error_outline,
                        color: Theme.of(context).colorScheme.error,
                        size: 18,
                      ),
                      const SizedBox(width: 8),
                      Expanded(child: Text(_error!)),
                    ],
                  ),
                ),
              ],
              const SizedBox(height: 32),
            ],
          ),
        ),
        ),
      ),
    );
  }

  /// Per-type input fields.
  ///
  ///   Article: title (required), body (required)
  ///   Video / Reel: title (optional), body (caption), mediaUrl (required),
  ///                 coverUrl (optional), durationSeconds (optional)
  /// Human-readable hint shown under the type picker — clarifies
  /// what each format is for so a first-time user picks correctly.
  /// Localized strings are deferred until the wider studio i18n
  /// pass — these are the same English copy used in the social
  /// hub.
  String _typeDescription(PostType t) {
    switch (t) {
      case PostType.article:
        return 'createPostX.descArticle'.tr;
      case PostType.video:
        return 'createPostX.descVideo'.tr;
      case PostType.reel:
        return 'createPostX.descReel'.tr;
    }
  }

  List<Widget> _fieldsForType() {
    final isArticle = _type == PostType.article;
    return [
      _SectionLabel('createPostX.labelTitle'.tr),
      const SizedBox(height: 6),
      TextFormField(
        controller: _title,
        decoration: InputDecoration(
          hintText: isArticle
              ? 'createPostX.hintHeadlineArticle'.tr
              : 'createPostX.hintHeadlineOptional'.tr,
        ),
        validator: (v) {
          if (isArticle && (v == null || v.trim().isEmpty)) return 'createPostX.required'.tr;
          return null;
        },
      ),
      const SizedBox(height: 16),
      _SectionLabel(isArticle ? 'createPostX.labelBody'.tr : 'createPostX.labelCaption'.tr),
      const SizedBox(height: 6),
      TextFormField(
        controller: _body,
        maxLines: isArticle ? 8 : 4,
        decoration: InputDecoration(
          hintText: isArticle
              ? 'createPostX.hintBodyArticle'.tr
              : 'createPostX.hintBodyCaption'.tr,
        ),
        validator: (v) {
          if (isArticle && (v == null || v.trim().isEmpty)) return 'createPostX.required'.tr;
          return null;
        },
      ),
      if (!isArticle) ...[
        const SizedBox(height: 16),
        _SectionLabel(_type == PostType.reel ? 'createPostX.labelReelVideo'.tr : 'createPostX.labelVideoFile'.tr),
        const SizedBox(height: 6),
        _MediaPickerTile(
          icon: Icons.videocam_rounded,
          emptyLabel: _type == PostType.reel
              ? 'createPostX.pickReelVideo'.tr
              : 'createPostX.pickVideoFile'.tr,
          uploading: _uploadingVideo,
          uploadProgress: _videoUploadProgress,
          uploadedUrl:
              _mediaUrl.text.trim().isEmpty ? null : _mediaUrl.text.trim(),
          localFile: _pickedVideoLocal,
          onPick: _pickAndUploadVideo,
          onRemove: _clearVideo,
        ),
        if (_duration.text.isNotEmpty) ...[
          const SizedBox(height: 6),
          Text(
            _type == PostType.reel
                ? 'createPostX.detectedDurationReel'
                    .trParams({'seconds': _duration.text})
                : 'createPostX.detectedDuration'
                    .trParams({'seconds': _duration.text}),
            style: Theme.of(context).textTheme.labelSmall?.copyWith(
                  color: Theme.of(context).colorScheme.onSurfaceVariant,
                ),
          ),
        ],
        const SizedBox(height: 16),
        _SectionLabel('createPostX.labelCover'.tr),
        const SizedBox(height: 6),
        _MediaPickerTile(
          icon: Icons.image_rounded,
          emptyLabel: 'createPostX.pickThumbnail'.tr,
          uploading: _uploadingCover,
          uploadedUrl:
              _coverUrl.text.trim().isEmpty ? null : _coverUrl.text.trim(),
          localFile: _pickedCoverLocal,
          onPick: _pickAndUploadCover,
          onRemove: _clearCover,
          // When the cover came from the auto-thumbnail extraction we
          // surface that to the user so they know it'll work without
          // them needing to pick anything — and that they can override.
          subtitleOverride: _coverIsAuto
              ? 'createPostX.coverAuto'.tr
              : null,
        ),
        if (_mediaPickError != null) ...[
          const SizedBox(height: 10),
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: Theme.of(context)
                  .colorScheme
                  .errorContainer
                  .withValues(alpha: 0.4),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Row(
              children: [
                Icon(Icons.error_outline,
                    color: Theme.of(context).colorScheme.error, size: 16),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    _mediaPickError!,
                    style: const TextStyle(fontSize: 12.5, height: 1.35),
                  ),
                ),
              ],
            ),
          ),
        ],
        // Invisible form gate so submit fails when no video URL has been
        // picked + uploaded yet. We previously used a `TextFormField` with
        // `style: TextStyle(fontSize: 0, height: 0)` to collapse it, but
        // Flutter 3.x adds a `fontSize == null || fontSize > 0` assertion
        // on `StrutStyle` that crashes the screen whenever this branch
        // builds (Studio → New Post → Reel). Use a `FormField<String>`
        // instead: it participates in Form.validate() the same way but
        // renders nothing unless there's an error to display.
        FormField<String>(
          validator: (_) {
            if (_mediaUrl.text.trim().isEmpty) {
              return _type == PostType.reel
                  ? 'createPostX.pickReelToUpload'.tr
                  : 'createPostX.pickVideoToUpload'.tr;
            }
            return null;
          },
          builder: (state) {
            final err = state.errorText;
            if (err == null) return const SizedBox.shrink();
            return Padding(
              padding: const EdgeInsets.only(top: 6),
              child: Text(
                err,
                style: TextStyle(
                  color: Theme.of(context).colorScheme.error,
                  fontSize: 12.5,
                  height: 1.35,
                ),
              ),
            );
          },
        ),
      ],
    ];
  }
}

/// Reusable picker tile — shows a "Pick…" button when empty, a thumbnail-ish
/// card when a file is picked + uploaded, and a spinner while uploading.
class _MediaPickerTile extends StatelessWidget {
  final IconData icon;
  final String emptyLabel;
  final bool uploading;
  /// 0..1 chunked-upload progress. When provided AND non-zero, the
  /// uploading state renders a real progress bar instead of a generic
  /// spinner. Cover uploads (single-shot) keep passing 0 / null and
  /// fall back to the spinner-only branch.
  final double? uploadProgress;
  final String? uploadedUrl;
  final File? localFile;
  final VoidCallback onPick;
  final VoidCallback onRemove;
  /// Optional override for the small subtitle under the filename when a
  /// file is uploaded. Used to mark the cover as auto-generated.
  final String? subtitleOverride;

  const _MediaPickerTile({
    required this.icon,
    required this.emptyLabel,
    required this.uploading,
    required this.uploadedUrl,
    required this.localFile,
    required this.onPick,
    required this.onRemove,
    this.uploadProgress,
    this.subtitleOverride,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    if (uploading) {
      // Use a determinate bar when chunked-upload progress is wired in
      // (videos). Cover / image uploads still pass null and get the
      // legacy spinner — that path is single-shot and there's no
      // progress to report.
      final hasProgress = uploadProgress != null && uploadProgress! > 0;
      final pct = hasProgress
          ? '${(uploadProgress!.clamp(0.0, 1.0) * 100).toStringAsFixed(0)}%'
          : null;
      return Container(
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: cs.surfaceContainerHighest.withValues(alpha: 0.4),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: cs.outlineVariant.withValues(alpha: 0.4)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                SizedBox(
                  width: 18,
                  height: 18,
                  child: hasProgress
                      ? CircularProgressIndicator(
                          strokeWidth: 2,
                          value: uploadProgress!.clamp(0.0, 1.0),
                        )
                      : const CircularProgressIndicator(strokeWidth: 2),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    pct == null
                        ? 'createPostX.uploading'.tr
                        : 'createPostX.uploadingPct'.trParams({'pct': pct}),
                    style: Theme.of(context).textTheme.bodyMedium,
                  ),
                ),
              ],
            ),
            if (hasProgress) ...[
              const SizedBox(height: 10),
              ClipRRect(
                borderRadius: BorderRadius.circular(4),
                child: LinearProgressIndicator(
                  minHeight: 4,
                  value: uploadProgress!.clamp(0.0, 1.0),
                  backgroundColor: cs.outlineVariant.withValues(alpha: 0.4),
                ),
              ),
            ],
          ],
        ),
      );
    }
    if (uploadedUrl != null) {
      final filename = localFile?.uri.pathSegments.last ?? 'createPostX.uploaded'.tr;
      return Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: cs.primary.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: cs.primary.withValues(alpha: 0.4)),
        ),
        child: Row(
          children: [
            Icon(Icons.check_circle_rounded, color: cs.primary, size: 20),
            const SizedBox(width: 10),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    filename,
                    overflow: TextOverflow.ellipsis,
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                          fontWeight: FontWeight.w700,
                        ),
                  ),
                  Text(
                    subtitleOverride ?? 'createPostX.uploaded'.tr,
                    style: Theme.of(context).textTheme.labelSmall?.copyWith(
                          color: cs.onSurfaceVariant,
                        ),
                  ),
                ],
              ),
            ),
            TextButton(
              onPressed: onPick,
              child: Text('createPostX.replace'.tr),
            ),
            IconButton(
              tooltip: 'createPostX.removeTooltip'.tr,
              icon: const Icon(Icons.close_rounded, size: 18),
              onPressed: onRemove,
            ),
          ],
        ),
      );
    }
    return InkWell(
      onTap: onPick,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 18),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: cs.outlineVariant.withValues(alpha: 0.55),
            style: BorderStyle.solid,
          ),
          color: cs.surfaceContainerHighest.withValues(alpha: 0.25),
        ),
        child: Row(
          children: [
            Container(
              width: 36,
              height: 36,
              decoration: BoxDecoration(
                color: cs.primary.withValues(alpha: 0.15),
                borderRadius: BorderRadius.circular(10),
              ),
              alignment: Alignment.center,
              child: Icon(icon, color: cs.primary, size: 20),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                emptyLabel,
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
              ),
            ),
            Icon(Icons.add_rounded, color: cs.primary),
          ],
        ),
      ),
    );
  }
}

class _SectionLabel extends StatelessWidget {
  final String text;
  const _SectionLabel(this.text);

  @override
  Widget build(BuildContext context) {
    return Text(
      text.toUpperCase(),
      style: Theme.of(context).textTheme.labelSmall?.copyWith(
            color: Theme.of(context).colorScheme.onSurfaceVariant,
            fontWeight: FontWeight.w700,
            letterSpacing: 1,
          ),
    );
  }
}

class _TypePicker extends StatelessWidget {
  final PostType value;
  final ValueChanged<PostType> onChange;
  const _TypePicker({required this.value, required this.onChange});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        for (final t in PostType.values) ...[
          Expanded(
            child: _SegmentTile(
              icon: switch (t) {
                PostType.article => Icons.article_outlined,
                PostType.video => Icons.video_collection_outlined,
                PostType.reel => Icons.movie_creation_outlined,
              },
              label: t.displayName,
              selected: t == value,
              onTap: () => onChange(t),
            ),
          ),
          if (t != PostType.values.last) const SizedBox(width: 8),
        ],
      ],
    );
  }
}

class _VisibilityPicker extends StatelessWidget {
  final PostVisibility value;
  final ValueChanged<PostVisibility> onChange;
  const _VisibilityPicker({required this.value, required this.onChange});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: _SegmentTile(
            icon: Icons.public,
            label: 'createPostX.visPublic'.tr,
            selected: value == PostVisibility.public,
            onTap: () => onChange(PostVisibility.public),
          ),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: _SegmentTile(
            icon: Icons.lock_outline,
            label: 'createPostX.visSubscribers'.tr,
            selected: value == PostVisibility.subscribersOnly,
            onTap: () => onChange(PostVisibility.subscribersOnly),
          ),
        ),
      ],
    );
  }
}

class _SegmentTile extends StatelessWidget {
  final IconData icon;
  final String label;
  final bool selected;
  final VoidCallback onTap;
  const _SegmentTile({
    required this.icon,
    required this.label,
    required this.selected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
        decoration: BoxDecoration(
          color: selected
              ? cs.primary.withValues(alpha: 0.18)
              : cs.surfaceContainerHighest.withValues(alpha: 0.4),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: selected ? cs.primary : Colors.transparent,
            width: 1.5,
          ),
        ),
        child: Column(
          children: [
            Icon(icon, color: selected ? cs.primary : cs.onSurfaceVariant),
            const SizedBox(height: 4),
            Text(
              label,
              style: Theme.of(context).textTheme.labelMedium?.copyWith(
                    color: selected ? cs.primary : cs.onSurfaceVariant,
                    fontWeight: FontWeight.w700,
                  ),
            ),
          ],
        ),
      ),
    );
  }
}

class _TickerInput extends StatelessWidget {
  final TextEditingController controller;
  final List<String> items;
  final ValueChanged<String> onAdd;
  final ValueChanged<int> onRemove;

  const _TickerInput({
    required this.controller,
    required this.items,
    required this.onAdd,
    required this.onRemove,
  });

  void _commit() {
    final raw = controller.text.trim();
    if (raw.isEmpty) return;
    onAdd(raw);
    controller.clear();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(
              child: TextField(
                controller: controller,
                decoration:
                    InputDecoration(hintText: 'createPostX.hintTickers'.tr),
                onSubmitted: (_) => _commit(),
                textCapitalization: TextCapitalization.characters,
              ),
            ),
            const SizedBox(width: 8),
            IconButton.filledTonal(
              onPressed: _commit,
              icon: const Icon(Icons.add),
            ),
          ],
        ),
        if (items.isNotEmpty) ...[
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              for (var i = 0; i < items.length; i++)
                InputChip(
                  label: Text(items[i]),
                  onDeleted: () => onRemove(i),
                ),
            ],
          ),
        ],
      ],
    );
  }
}

// ─── Destination picker ─────────────────────────────────────────────
//
// "Publish to" section in the create-post composer. Lists:
//   * the expert's own profile (always present, default ON)
//   * every community the expert has joined
//
// Communities lock to a disabled state when [communitiesEnabled] is
// false — currently triggered when the post type is video or reel
// because the community endpoint only accepts article-shaped bodies
// (no mediaUrl / coverUrl).
class _DestinationPicker extends StatelessWidget {
  final bool publishToProfile;
  final ValueChanged<bool> onProfileChange;
  final List<mock.Community> destinations;
  final Set<String> selectedCommunities;
  final ValueChanged<String> onCommunityToggle;
  final bool loaded;
  final bool communitiesEnabled;

  const _DestinationPicker({
    required this.publishToProfile,
    required this.onProfileChange,
    required this.destinations,
    required this.selectedCommunities,
    required this.onCommunityToggle,
    required this.loaded,
    required this.communitiesEnabled,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return Container(
      decoration: BoxDecoration(
        color: cs.surfaceContainerHighest.withValues(alpha: 0.4),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: cs.outlineVariant.withValues(alpha: 0.5)),
      ),
      child: Column(
        children: [
          // Profile row — always there.
          _DestRow(
            checked: publishToProfile,
            onTap: () => onProfileChange(!publishToProfile),
            leading: Icon(Icons.person_rounded, size: 18, color: cs.primary),
            label: 'createPostX.yourProfile'.tr,
            sublabel: 'createPostX.yourProfileSub'.tr,
            tint: cs.primary,
          ),
          if (loaded && destinations.isNotEmpty)
            Container(
              height: 0.6,
              margin: const EdgeInsets.symmetric(horizontal: 12),
              color: cs.outlineVariant.withValues(alpha: 0.4),
            ),
          if (!loaded)
            Padding(
              padding: const EdgeInsets.all(14),
              child: Row(
                children: [
                  SizedBox(
                    width: 14,
                    height: 14,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      color: cs.primary,
                    ),
                  ),
                  const SizedBox(width: 10),
                  Text(
                    'createPostX.loadingCommunities'.tr,
                    style: TextStyle(
                      color: cs.onSurfaceVariant,
                      fontSize: 12.5,
                    ),
                  ),
                ],
              ),
            ),
          // One row per community the expert has joined.
          for (final c in destinations) ...[
            _DestRow(
              checked: selectedCommunities.contains(c.id),
              onTap: communitiesEnabled
                  ? () => onCommunityToggle(c.id)
                  : null,
              leading: Container(
                width: 22,
                height: 22,
                alignment: Alignment.center,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: SocialTokens.regionColor(c.regionCode)
                      .withValues(alpha: 0.18),
                  border: Border.all(
                    color: SocialTokens.regionColor(c.regionCode),
                    width: 1,
                  ),
                ),
                child: Text(
                  c.regionCode.isEmpty ? '·' : c.regionCode.substring(0, 1),
                  style: TextStyle(
                    color: SocialTokens.regionColor(c.regionCode),
                    fontWeight: FontWeight.w900,
                    fontSize: 10,
                  ),
                ),
              ),
              label: c.name,
              sublabel: communitiesEnabled
                  ? c.regionCode
                  : 'createPostX.articlesOnly'.tr,
              tint: SocialTokens.regionColor(c.regionCode),
              dimmed: !communitiesEnabled,
            ),
          ],
        ],
      ),
    );
  }
}

class _DestRow extends StatelessWidget {
  final bool checked;
  final VoidCallback? onTap;
  final Widget leading;
  final String label;
  final String sublabel;
  final Color tint;
  final bool dimmed;

  const _DestRow({
    required this.checked,
    required this.onTap,
    required this.leading,
    required this.label,
    required this.sublabel,
    required this.tint,
    this.dimmed = false,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return Opacity(
      opacity: dimmed ? 0.45 : 1.0,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(8),
        child: Padding(
          padding: const EdgeInsets.fromLTRB(12, 10, 12, 10),
          child: Row(
            children: [
              leading,
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      label,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                        fontWeight: FontWeight.w800,
                        fontSize: 13,
                      ),
                    ),
                    const SizedBox(height: 1),
                    Text(
                      sublabel,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                        color: cs.onSurfaceVariant,
                        fontSize: 11,
                      ),
                    ),
                  ],
                ),
              ),
              // Right-side checkmark — accent-tinted when on,
              // hollow circle when off. We avoid the default
              // Checkbox to keep the tap target identical between
              // checked/unchecked states.
              Container(
                width: 22,
                height: 22,
                alignment: Alignment.center,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: checked
                      ? tint.withValues(alpha: 0.18)
                      : Colors.transparent,
                  border: Border.all(
                    color: checked
                        ? tint
                        : cs.outlineVariant.withValues(alpha: 0.7),
                    width: checked ? 1.4 : 1,
                  ),
                ),
                child: checked
                    ? Icon(Icons.check_rounded, size: 14, color: tint)
                    : null,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _StancePicker extends StatelessWidget {
  final String value; // BUY | HOLD | SELL
  final ValueChanged<String> onChange;

  const _StancePicker({required this.value, required this.onChange});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        for (final s in const ['BUY', 'HOLD', 'SELL'])
          Expanded(
            child: Padding(
              padding: const EdgeInsetsDirectional.only(end: 6),
              child: _StanceTile(
                label: s,
                selected: value == s,
                tint: s == 'BUY'
                    ? SocialTokens.up
                    : s == 'SELL'
                        ? SocialTokens.down
                        : SocialTokens.gold,
                onTap: () => onChange(s),
              ),
            ),
          ),
      ],
    );
  }
}

class _StanceTile extends StatelessWidget {
  final String label;
  final bool selected;
  final Color tint;
  final VoidCallback onTap;

  const _StanceTile({
    required this.label,
    required this.selected,
    required this.tint,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(10),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 10),
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: selected ? tint.withValues(alpha: 0.18) : Colors.transparent,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: selected ? tint : cs.outlineVariant.withValues(alpha: 0.5),
            width: selected ? 1.4 : 1,
          ),
        ),
        child: Text(
          label,
          style: TextStyle(
            color: selected ? tint : cs.onSurfaceVariant,
            fontWeight: FontWeight.w900,
            fontSize: 12,
            letterSpacing: 0.6,
          ),
        ),
      ),
    );
  }
}

// ─── Visual scaffolding for the editorial composer redesign ────────

/// Soft-bordered card wrapper used for each step of the composer
/// (Format / Content / Tickers / Audience). Replaces the old flat
/// SectionLabel + content layout — gives the form real visual
/// hierarchy without going full Material-3 elevated card (which
/// looked too heavy on mobile).
class _Card extends StatelessWidget {
  final String title;
  /// Optional small chip on the right of the title bar — used to
  /// surface a dynamic count (e.g. "2" for 2 tickers picked).
  final String? titleSuffix;
  final Widget child;

  const _Card({
    required this.title,
    required this.child,
    this.titleSuffix,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return Container(
      decoration: BoxDecoration(
        color: cs.surfaceContainerHighest.withValues(alpha: 0.32),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: cs.outlineVariant.withValues(alpha: 0.5),
          width: 0.8,
        ),
      ),
      padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  title.toUpperCase(),
                  style: Theme.of(context).textTheme.labelSmall?.copyWith(
                        color: cs.onSurfaceVariant,
                        fontWeight: FontWeight.w900,
                        letterSpacing: 1.2,
                      ),
                ),
              ),
              if (titleSuffix != null)
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 7,
                    vertical: 2,
                  ),
                  decoration: BoxDecoration(
                    color: cs.primary.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(
                    titleSuffix!,
                    style: TextStyle(
                      color: cs.primary,
                      fontWeight: FontWeight.w900,
                      fontSize: 10.5,
                    ),
                  ),
                ),
            ],
          ),
          const SizedBox(height: 12),
          child,
        ],
      ),
    );
  }
}

/// Smaller secondary label used INSIDE a card (e.g. "Visibility"
/// and "Publish to" inside the Audience card). Separate from
/// _SectionLabel so the visual weight sits below the card title
/// without competing with it.
class _SubLabel extends StatelessWidget {
  final String text;
  const _SubLabel(this.text);

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: Theme.of(context).textTheme.bodySmall?.copyWith(
            color: Theme.of(context).colorScheme.onSurfaceVariant,
            fontWeight: FontWeight.w800,
            fontSize: 11.5,
            letterSpacing: 0.3,
          ),
    );
  }
}
