ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_tier VARCHAR(20) DEFAULT 'FREE';
ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(20) DEFAULT 'ACTIVE';
-- ACTIVE, CANCELED, EXPIRED
ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_end_date TIMESTAMP;