import 'dart:async';
import 'dart:ui';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_phoenix/flutter_phoenix.dart';
import 'package:get/get.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'firebase_options.dart';
import 'localization/app_translations.dart';

import 'controllers/auth_controller.dart';
import 'controllers/chat_presence_controller.dart';
import 'controllers/currency_controller.dart';
import 'controllers/feed_controller.dart';
import 'controllers/language_controller.dart';
import 'controllers/mute_controller.dart';
import 'controllers/notifications_controller.dart';
import 'controllers/realtime_controller.dart';
import 'controllers/saved_controller.dart';
import 'controllers/stocks_controller.dart';
import 'controllers/subscription_controller.dart';
import 'controllers/theme_controller.dart';
import 'controllers/watchlist_controller.dart';
import 'main_tab_scaffold.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/onboarding_screen.dart';
import 'screens/splash/splash_screen.dart';
import 'services/deep_link_service.dart';
import 'services/iap_service.dart';
import 'services/push_token_service.dart';
import 'services/tracking_service.dart';
import 'theme/halal_fintech_theme.dart';
import 'widgets/social/community_message_banner.dart';

Future<void> main() async {
  // Bind the Flutter engine before we await anything — Firebase.initializeApp
  // touches platform channels (iOS UIApplication, Android Activity) so the
  // binding must exist first or initialization throws.
  WidgetsFlutterBinding.ensureInitialized();

  // Date-symbol data for non-system locales (Arabic month/day names). Must
  // run before any DateFormat(..., 'ar') call (see LocaleFormat). Cheap.
  await initializeDateFormatting();

  // Firebase is the OAuth bridge for Google + Apple sign-in (see
  // controllers/auth_controller.dart). It must be ready before AuthController
  // is constructed because that controller subscribes to
  // FirebaseAuth.instance.authStateChanges on boot.
  //
  // DefaultFirebaseOptions.currentPlatform is generated by `flutterfire
  // configure` (lib/firebase_options.dart). It picks the iOS or Android
  // config struct at runtime based on defaultTargetPlatform.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Crashlytics — forward every uncaught Dart error to Firebase so the
  // console shows the same stack traces we'd see locally. Disabled in
  // debug so the IDE's red-screen + console still own the dev loop.
  //
  // `recordFlutterFatalError` reports framework-level errors (build
  // exceptions, layout overflows tripped by an `assert`, etc.) as
  // fatal so they bubble up to the dashboard's crash count, not the
  // non-fatal log.
  await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(!kDebugMode);
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  // Push notification token bootstrap. Fires asynchronously — we
  // don't await it so a slow APNs handshake on first launch can't
  // block the splash screen. The service logs the token to the debug
  // console via debugPrint('[push] FCM token: ...').
  unawaited(PushTokenService.instance.bootstrap());

  // In-app-purchase plugin connection. Same fire-and-forget pattern —
  // talks to StoreKit on iOS / Play Billing on Android, listens to the
  // purchase stream for the rest of the session, and verifies receipts
  // against /api/me/iap/apple/verify when they arrive.
  unawaited(IAPService.instance.bootstrap());

  // Register all controllers up-front so any screen can `Get.find<X>()` them.
  // permanent: true keeps them alive for the whole app lifetime — they hold
  // session/preferences data we never want re-bootstrapped on a route change.
  Get.put(AuthController(), permanent: true);
  Get.put(ThemeController(), permanent: true);
  Get.put(LanguageController(), permanent: true);
  Get.put(StocksController(), permanent: true);
  Get.put(WatchlistController(), permanent: true);
  Get.put(CurrencyController(), permanent: true);
  // Realtime depends on AuthController being already registered — it watches
  // the auth state to know when to (re)connect the WebSocket.
  Get.put(RealtimeController(), permanent: true);
  // Subscriptions depend on RealtimeController for live state updates.
  Get.put(SubscriptionController(), permanent: true);
  // Feed tab — aggregates posts from active subscriptions. Listens on the
  // realtime stream + auth lifecycle, so it must register after both.
  Get.put(FeedController(), permanent: true);
  // Notifications inbox — bell badge + screen list. Same dependency chain
  // as the Feed controller (realtime + auth).
  Get.put(NotificationsController(), permanent: true);
  // Saved posts — single source of truth for "is post X bookmarked?"
  // across every card, plus the saved-posts screen list.
  Get.put(SavedController(), permanent: true);
  // Tracks the community whose chat the user is currently viewing —
  // drives the global new-message banner so we don't toast a chat
  // the user is already reading.
  Get.put(ChatPresenceController(), permanent: true);
  // Per-device mute state for community chat banners. SharedPreferences-
  // backed, hydrated lazily on first construction.
  Get.put(MuteController(), permanent: true);

  // Phoenix wraps the entire app so we can trigger a clean restart whenever
  // the user's role changes (`Phoenix.rebirth(context)` rebuilds the tree
  // from scratch — all controllers + widget state are re-bootstrapped).
  runApp(Phoenix(child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Get.find<ThemeController>();
    final lang = Get.find<LanguageController>();

    return Obx(() {
      final locale = lang.locale;
      final isDark = theme.isDarkMode;
      return GetMaterialApp(
        title: 'Halal Stocks',
        debugShowCheckedModeBanner: false,
        theme: HalalFintechTheme.lightTheme(locale.languageCode),
        darkTheme: HalalFintechTheme.darkTheme(locale.languageCode),
        themeMode: isDark ? ThemeMode.dark : ThemeMode.light,
        translations: AppTranslations(),
        locale: locale,
        fallbackLocale: const Locale('en'),
        supportedLocales: const [Locale('en'), Locale('ar')],
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        builder: (context, child) {
          // The banner Stack wraps the whole app so it overlays every
          // route — login screen, splash, deep-linked post viewer, the
          // bottom-nav scaffold, etc. It only renders when a fresh
          // `community_message` realtime event lands.
          return Directionality(
            textDirection: locale.languageCode == 'ar'
                ? TextDirection.rtl
                : TextDirection.ltr,
            child: CommunityMessageBanner(child: child!),
          );
        },
        home: const _AppEntry(),
        getPages: [
          GetPage(name: '/login', page: () => const LoginScreen()),
        ],
      );
    });
  }
}

/// Boots into the splash screen, holds it for a minimum brand-impression time
/// AND until [AuthController] has finished loading the persisted token, then
/// hands off to the right destination (login vs main tab scaffold).
class _AppEntry extends StatefulWidget {
  const _AppEntry();

  @override
  State<_AppEntry> createState() => _AppEntryState();
}

class _AppEntryState extends State<_AppEntry> {
  // Minimum splash hold. Bumped to 3200ms when the splash was redesigned
  // to "Live Market Pulse" — the new entrance choreography is 3.2s, so
  // anything less cut off the candlestick draw + shine sweep mid-flight.
  static const _splashMin = Duration(milliseconds: 3200);
  bool _splashReady = false;

  @override
  void initState() {
    super.initState();
    Future.delayed(_splashMin, () {
      if (mounted) setState(() => _splashReady = true);
      // App Tracking Transparency. iOS surfaces a system modal here;
      // calling it post-splash means the brand impression lands first.
      // Fire-and-forget — never block the handoff to the main tab
      // scaffold on the user dismissing the prompt.
      unawaited(TrackingService.instance.requestIfNeeded());
    });
    // Wire up deep-link routing once the first frame is on screen — at
    // that point the navigator is mounted, so a cold-start `unmu.app/p/:id`
    // URL can push the post viewer on top of the splash / main scaffold.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      DeepLinkService.instance.init();
    });
  }

  @override
  Widget build(BuildContext context) {
    final auth = Get.find<AuthController>();
    return Obx(() {
      // Read every reactive value up-front so Obx's dependency tracker sees
      // them even when boolean short-circuits skip later reads. Without this,
      // when `!_splashReady` is true the `||` short-circuits and Obx records
      // zero observable reads, throwing "improper use of a GetX has been
      // detected" on first build.
      final authChecked = auth.authChecked;
      final isAuthed = auth.isAuthenticated;
      // A first-time Google/Apple user who hasn't set a password yet —
      // show the onboarding screen (set name + password) before the app.
      final needsOnboarding = auth.needsOnboarding;

      // Show splash until BOTH (a) the minimum brand-impression timer fires
      // and (b) the auth controller finished its persisted-token check.
      final showSplash = !_splashReady || !authChecked;

      return AnimatedSwitcher(
        duration: const Duration(milliseconds: 380),
        switchInCurve: Curves.easeOut,
        switchOutCurve: Curves.easeIn,
        child: showSplash
            ? const SplashScreen(key: ValueKey('splash'))
            : (isAuthed
                  ? (needsOnboarding
                      ? const OnboardingScreen(key: ValueKey('onboarding'))
                      : const MainTabScaffold(key: ValueKey('main')))
                  : const LoginScreen(key: ValueKey('login'))),
      );
    });
  }
}
